@baseurl = https://localhost:5001

###

GET {{baseurl}}/weatherforecast/ HTTP/1.1

###

GET {{baseurl}}/weatherforecast/id/2 HTTP/1.1

###

POST {{baseurl}}/weatherforecast HTTP/1.1
Content-Type: application/json

{
    "title": "Wash the dog"
}

### 

PUT {{baseurl}}/weatherforecast/id/3 HTTP/1.1
Content-Type: application/json

{
    "title": "Feed the fish"
}

###

DELETE {{baseurl}}/weatherforecast/id/3 HTTP/1.1