# [Choice] .NET version: 6.0-bullseye, 5.0-bullseye, 3.1-bullseye, 6.0-focal, 5.0-focal, 3.1-focal
# https://mcr.microsoft.com/v2/dotnet/sdk/tags/list
ARG VARIANT=6.0-bullseye-slim
FROM mcr.microsoft.com/dotnet/sdk:${VARIANT}
