@hostname = localhost:5001
@version = v1
@base_url = https://{{hostname}}/api/{{version}}

###

// GET all the cocktails available to serve.
GET {{base_url}}/cocktails HTTP/1.1

### 

// POST create a cocktail from another with minimal payload.
// @name rebrand
POST {{base_url}}/cocktails/code/b052/rebrand HTTP/1.1
Content-Type: application/json

{
    "originCode": "b052",
    "code": "b007",
    "displayName": "Last Words",
    "value": 7
}
###
GET {{rebrand.response.headers.Location}} HTTP/1.1
###

// POST rebarnd a cocktail from another and discontinue.
// @name rebrand_discontinue
POST {{base_url}}/cocktails/code/b052/rebrand HTTP/1.1
Content-Type: application/json

{
    "originCode": "b052",
    "code": "p071",
    "displayName": "Pimm's Cup",
    "value": 4.5,
    "seasonal": true,
    "discontinueOrigin": true
}
###
GET {{rebrand_discontinue.response.headers.Location}} HTTP/1.1
### 

// DELETE discontinue a cocktail (soft-delete).
DELETE {{base_url}}/cocktails/code/h002/discontinue HTTP/1.1
Content-Type: application/json

###

// POST order a bunch of cocktails.
// @name post_orders
POST {{base_url}}/orders HTTP/1.1
Content-Type: application/json

{
    "discount": 4.5,
    "items": [
        { "code": "c043", "quantity": 2 },
        { "code": "b007", "quantity": 1 },
        { "code": "f075", "quantity": 2, "discount": 2 }
    ]
}
###
GET {{post_orders.response.headers.Location}} HTTP/1.1
###