
GET https://localhost:5001/api/v1/products HTTP/1.1

###

GET https://localhost:5001/api/v1/purchasing/orders/id/1 HTTP/1.1

###

POST https://localhost:5001/api/v1/purchasing/orders HTTP/1.1
Content-Type: application/json

{
    "supplierId": 2,
    "orderedItems": {
        "COF87992": 6
    }
}